[package]
name = "ssurlss"
version = "1.0.0"
edition = "2021"

[dependencies]
html-escape = "0.2.13"
random-string = "1.1.0"
serde = { version = "1.0.213", features = ["derive"] }
tiny_http = "0.12.0"
toml = "0.8.19"
