[package]
name = "ssurlss"
version = "1.1.0"
edition = "2021"

[dependencies]
random-string = "1.1.0"
serde = { version = "1.0.213", features = ["derive"] }
tiny_http = "0.12.0"
toml = "0.8.19"
urlencoding = "2.1.3"
